Updated zsh config

diff --git a/zsh/zshrc b/zsh/zshrc
--- a/zsh/zshrc
+++ b/zsh/zshrc
@@ -1,159 +1,141 @@
-# {{{ Zsh options
-setopt appendhistory
-setopt extendedglob
-setopt nobeep
-setopt autocd
-setopt autopushd
-setopt pushdignoredups
-setopt pushdsilent
-setopt correct
-setopt notify
-setopt hash_list_all
-setopt completeinword
-setopt nohup
-setopt dvorak
-setopt prompt_subst
-# }}}
+# -*- mode: sh; sh-shell: zsh; -*-
 
-# {{{ Environment
-eval `dircolors -b`
-export ZSHDIR=$HOME/.zsh
+WORDCHARS='*?_-.[]~&;!#$%^(){}<>'
 HISTFILE=~/.histfile
-HISTSIZE=1000
-SAVEHIST=1000
-DIRSTACKSIZE=6
-REPORTTIME=5
-
-export TEXDOC_VIEWER_PDF='(evince %s)&'
-export LESSCHARSET=utf-8
-export PATH=${PATH}:${HOME}/bin;
-export BROWSER=/home/kanru/bin/myfx.sh
-export DEBEMAIL="koster@debian.org.tw"
-export DEBFULLNAME="Kanru Chen"
-export EMAIL="kanru@kanru.info"
-export EDITOR=vim
-export LESS_TERMCAP_mb=$'\E[01;31m'
-export LESS_TERMCAP_md=$'\E[01;31m'
-export LESS_TERMCAP_me=$'\E[0m'
-export LESS_TERMCAP_se=$'\E[0m'
-export LESS_TERMCAP_so=$'\E[01;44;33m'
-export LESS_TERMCAP_ue=$'\E[0m'
-export LESS_TERMCAP_us=$'\E[01;32m'
-#export DEBCVS=:pserver:kanru@cvs.debian.org:/cvs/webwml
-# }}}
-
-# {{{ keybindings
+HISTSIZE=2000
+SAVEHIST=2000
+setopt share_history hist_reduce_blanks hist_no_functions hist_ignore_space
+setopt append_history histignorealldups dvorak
+setopt nohashcmds autocd notify prompt_subst nobeep
 bindkey -e
-# }}}
+autoload edit-command-line && zle -N edit-command-line
+bindkey '\ee' edit-command-line
 
-# {{{ Completition stuff
-autoload -Uz compinit
-compinit
-
-#zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
-## correction
-
-# Ignore completion functions for commands you don't have:
-#  zstyle ':completion:*:functions' ignored-patterns '_*'
-zstyle ':completion::(^approximate*):*:functions' ignored-patterns '_*'
-
-zstyle ':completion:*'             completer _complete _prefix _correct _approximate
-zstyle ':completion:*' matcher-list '' 'm:{a-zA-Z}={A-Za-z}'
-zstyle ':completion:*:correct:*'   insert-unambiguous true
-#  zstyle ':completion:*:corrections' format '%B%d (errors: %e)%b'
-#  zstyle ':completion:*:corrections' format $'%{\e[0;31m%}%d (errors: %e)%}'
-zstyle ':completion:*:corrlctions' format $'%d (errors: %e)'
-zstyle ':completion:*:correct:*'   original true
-zstyle ':completion:correct:'      prompt 'correct to:'
-
-# command for process lists, the local web server details and host completion
+# ZSH COMPLETION
+autoload -U compinit && compinit
+zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
+zstyle ':completion:*' use-cache on
+zstyle ':completion:*' cache-path ~/.zsh/cache
+zstyle ':completion:*' completer _complete _correct _complete:foo
+zstyle ':completion:*:complete:*' matcher-list '' 'm:{a-zA-Z}={A-Za-z}'
+zstyle ':completion:*:foo:*' matcher-list 'm:{a-zA-Z}={A-Za-z} r:|[-_./]=* r:|=*'
+zstyle ':completion:*:functions' ignored-patterns '_*'
 hosts=(`hostname`)
 zstyle '*' hosts $hosts
-zstyle ':completion:*:urls' local 'www' '/var/www/' 'public_html'
-[ -d $ZSHDIR/cache ] && zstyle ':completion:*' use-cache on && \
-    zstyle ':completion::complete:*' cache-path $ZSHDIR/cache/
 # use ~/.ssh/known_hosts for completion
 [ -f "$HOME/.ssh/known_hosts" ] && \
     hosts=(${${${(f)"$(<$HOME/.ssh/known_hosts)"}%%\ *}%%,*}) && \
     zstyle ':completion:*:hosts' hosts $hosts
-#compdef _gnu_generic tail head feh cp mv gpg df stow uname ipacsum fetchipac
-# }}}
 
-# End of lines added by compinstall
-alias cls='ls -v --color=auto'
-alias rm='rm -i'
-alias cp='cp -i'
-alias mv='mv -i'
-alias ll='cls -l'
-alias la='cls -A'
-alias l='cls -CF'
-alias ii='cls -l'
-alias ic='cls --color'
-alias ia='cls -A'
-alias i='cls -C'
-alias c='clear'
-alias e='vim'
-alias g='wget'
-alias m='mplayer'
-alias t='telnet'
-alias n='host'
-alias s='ssh'
-alias mk='make'
-alias svnlog='svn log|less'
-alias acs='apt-cache search'
-alias api='sudo aptitude install'
-alias acsh='apt-cache show'
-alias au='sudo aptitude update'
-alias sa='sudo aptitude'
-alias tlog='tail -f /var/log/syslog'
-alias smi='sudo make install'
-alias sdi='sudo dpkg -i'
-alias grep='grep --color'
-alias src='cd ~src'
-alias gi='gvim --remote-tab'
+zle_highlight=(region:standout special:standout suffix:fg=red isearch:underline)
 
-# {{{ Set prompt
-# PS1=$'%{\e[1;33m%}%*%{\e[0m%} %{\e[1;31m%}%n%{\e[1;34m%}@%m:%{\e[32m%}%~ ^%j\n%{\e[1;33m%}%#%{\e[0m%} '
-autoload -Uz vcs_info
-zstyle ':vcs_info:*' actionformats \
-'%F{5}(%f%s%F{5})%F{3}-%F{5}[%F{2}%b%F{3}|%F{1}%a%F{5}]%f '
-zstyle ':vcs_info:*' formats       \
-'%F{5}(%f%s%F{5})%F{3}-%F{5}[%F{2}%b%F{5}]%f '
+# Include aliases and hashes
+[ -e ~/.zshalias  ] && source ~/.zshalias
+[ -e ~/.zshhashes ] && source ~/.zshhashes
+
+# vcs_info
+autoload -U vcs_info
+zstyle ':vcs_info:*' actionformats '%F{5}(%f%s%F{5})%F{3}-%F{5}[%F{2}%b%F{3}|%F{1}%a%F{5}]%f '
+zstyle ':vcs_info:*' formats '%F{5}(%f%s%F{5})%F{3}-%F{5}[%F{2}%b%F{5}]%f '
 zstyle ':vcs_info:(sv[nk]|bzr):*' branchformat '%b%F{1}:%F{3}%r'
 precmd () { vcs_info }
-EXITCODE="%(?..%?%1v )"
+
+# Prompt
+autoload -U colors && colors
+EXITCODE="%(?. . [%?]%1v)"
 JOBS="%(1j.%j .)"
-local BLUE="%{[1;34m%}"
-local RED="%{[1;31m%}"
-local GREEN="%{[1;32m%}"
-local CYAN="%{[1;36m%}"
-local YELLOW="%{[1;33m%}"
-local NO_COLOUR="%{[0m%}"
-PS2='`%_> '       # secondary prompt, printed when the shell needs more information to complete a command.
-PS3='?# '         # selection prompt used within a select loop.
-PS4='+%N:%i:%_> ' # the execution trace prompt (setopt xtrace). default: '+%N:%i>'
+PS2='`%_> '
+PS3='?# '
+PS4='+%N:%i:%_> '
+PROMPT="%{$fg[cyan]%}${JOBS}%{$fg_bold[red]%}${debian_chroot:+($debian_chroot)}%n%{$fg[blue]%}@%m:%{$fg_no_bold[green]%}%50<...<%~%<<"'${vcs_info_msg_0_}'"%{$fg[red]%}${EXITCODE}%{$reset_color%}
+%{$fg[red]%}%# %{$reset_color%}"
 
-PROMPT="${RED}${EXITCODE}${CYAN}${JOBS}${YELLOW}%* ${RED}%n${BLUE}@%m:${GREEN}%40<...<%B%~%b%<<"'${vcs_info_msg_0_}'"
-${YELLOW}%# ${NO_COLOUR}"
-
-# }}}
-
-hash -d deb=/var/cache/apt/archives
-hash -d doc=/usr/share/doc
-hash -d linux=/lib/modules/$(command uname -r)/build/
-hash -d log=/var/log
-hash -d src=/usr/src
-
-
-function 0 {
-	wget -c http://0rz.tw/$1;
+# Directory based profile, taken from grmlzshrc
+CHPWD_PROFILE='default'
+function chpwd_profiles() {
+    local -x profile
+    zstyle -s ":chpwd:profiles:${PWD}" profile profile || profile='default'
+    if (( ${+functions[chpwd_profile_$profile]} )) ; then
+        print "Switching to profile: $profile"
+        chpwd_profile_${profile}
+    fi
+    CHPWD_PROFILE="${profile}"
+    return 0
 }
-function mydict () {
-    dictl "$@" 2>&1 | colorit | less -R ;
+chpwd_functions=( ${chpwd_functions} chpwd_profiles )
+
+zstyle ":chpwd:profiles:$HOME/zone2/mozilla(|/|/*)" profile mozilla
+zstyle ":chpwd:profiles:$HOME/zone2/0xlab(|/|/*)"   profile 0xlab
+zstyle ":chpwd:profiles:$HOME/zone2/debian(|/|/*)"  profile debian
+
+function chpwd_profile_default() {
+    # TODO: auto unset
+    unset QUILT_PATCHES
+    [ -e ~/.zshenv  ] && source ~/.zshenv
 }
-function dormvga () {
-    xrandr --output VGA --mode 1024x768 --below LVDS;
+
+function chpwd_profile_0xlab() {
+    chpwd_profile_default
+
+    export GIT_AUTHOR_EMAIL="kanru@0xlab.org"
+    export GIT_COMMITTER_EMAIL="kanru@0xlab.org"
 }
-function labvga () {
-    xrandr --output VGA --mode 1280x1024 --below LVDS;
+
+function chpwd_profile_debian() {
+    chpwd_profile_default
+
+    export GIT_AUTHOR_EMAIL="koster@debian.org"
+    export GIT_COMMITTER_EMAIL="koster@debian.org"
+    export QUILT_PATCHES=debian/patches
 }
+
+function chpwd_profile_mozilla() {
+    chpwd_profile_default
+}
+
+# For stupid emacs Tramp mode
+if [ "$TERM" = "dumb" ]
+then
+  unsetopt zle
+  unsetopt prompt_cr
+  unsetopt prompt_subst
+  unfunction precmd
+  unfunction preexec
+  PS1='$ '
+fi
+
+# Recursively find the the toplevel Makefile or build.xml and call
+# make(1) or ant(1) accordingly
+function mk() {
+    if [ -f Makefile ]; then
+        make $@
+    elif [ -f build.xml ]; then
+        ant $@
+    else
+        local D=$PWD/..
+        while ! [ -f $D/Makefile -o -f $D/build.xml ]; do
+            D=$D/..
+            if [ $(readlink -f $D) = "/" ]; then
+                echo "Cannot find any Makefile or build.xml"
+                return 1
+            fi
+        done
+        if [ -f $D/Makefile ]; then
+            make -C $D $@
+        elif [ -f $D/build.xml ]; then
+            ant -f $D/build.xml $@
+        fi
+    fi
+}
+
+# Usage: .. [level]
+# Go up $level directories
+function ..() {
+    num=$1
+    test $1 || num=1
+    cd $(seq $num|xargs printf '../%.0s')
+    i
+}
+
+# Usage: = [math expression]
+function "="() { echo "$@" | bc -l; }
